title: Group 2 Presents
logo: https://raw.githubusercontent.com/DimonnPokemonn/Solitaire-Game/main/screenshots/logo.png
description: Card game
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
